apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentdetails
  labels:
    app: studentdetails
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: studentdetails
  template:
    metadata:
      labels:
        app: studentdetails
    spec:
      containers:
      - name: studentdetails
        image: purushothamkdr453/studentdetails:green 
        ports:
        - name: details
          containerPort: 5000
